apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: learnjenkins
build:
  local:
    useBuildkit: yes
  artifacts:
  - image: mikhailgostev/echo
    context: echo
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/echo-deploy.yaml
    - k8s/censor-svc.yaml
    - k8s/echo-svc.yaml
